# Generated by Django 5.2.1 on 2025-06-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('icon', models.URLField()),
            ],
        ),
    ]
