# Generated by Django 5.2.1 on 2025-06-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('rating', models.CharField(choices=[('yaxshi', 'Yaxshi'), ('alo', 'Alo'), ('qoniqarli', 'Qoniqarli')], default='yaxshi')),
                ('comment', models.TextField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
